# Generated by Django 4.1.5 on 2023-01-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloguers',
            new_name='Bloguer',
        ),
    ]
